### ISSUE TITLE
Better how-to for Twitter credentials?

### ISSUE THREAD

**Issue by jsvine** [jsvine/twick#1]
Right now, the [Twick README](https://github.com/jsvine/twick/blob/master/README.md#setup) points people to a StackOverflow answer, the most concise explanation I could find. Is there a better one out there? If not, is it worth creating one for future reference in this and other projects?

**Comment by dannguyen** [comment]
I haven't done the process from scratch in awhile, but here are the illustrated notes I made for my class: http://www.compjour.org/tutorials/getting-started-with-tweepy/
 
Feel free to reapproritate the text and assets as you wish.
 
I personally use a command-line script to go through the access-token generation process. But AFAIK, the initialization of the application has to be done via web browser.

**Comment by jsvine** [comment]
Thanks! Very helpful. Added a link.
