### ISSUE TITLE
Duplicates managment

### ISSUE THREAD

**Issue by aborruso** [jsvine/twick#5]
Jeremy, you are great.

Does your script remove the duplicate items? If I fetch every 5 minutes (it's an example) probably I will obtain some duplicate. Do I will have duplicate in my table?

Thank you

**Comment by jsvine** [comment]
Thanks, @aborruso! And, yes, `twick` only logs each tweet once. (Retweets of a tweet, though, will show up.)

**Comment by aborruso** [comment]
Thank you!
