### ISSUE TITLE
Tweets Table is not being populated

### ISSUE THREAD

**Issue by azanbinzahid** [jsvine/twick#6]
Hi,

I believe this repo isn't been touched for a while now but I can see response table getting filling in SQL but not tweets. Is there anything I am missing? I can see in cli that 100 tweets found but in SQL I can't see any.

Waiting for an answer, thanks!

**Comment by jsvine** [comment]
Hello, and yes, this library is no longer actively being maintained. It's possible that the API has changed to the point where this library's logic no longer works properly, so I will mark this repository as "archived." Thank you for the reminder.

**Comment by azanbinzahid** [comment]
Sounds good, thank you for the update.
